export const users = [
  {
    key: "1",
    name: "Ertuğrul",
    surname: "Başköy",
    email: "test@gmail.com",
    phone: "+90 555 555 55 55" ,
    age: 32,
    adress: "New York No. 1 Lake Park",
  },
  {
    key: "2",
    name: "Ertuğrul",
    surname: "Başköy",
    email: "test@gmail.com",
    phone: "+90 555 555 55 55" ,
    age: 32,
    adress: "New York No. 1 Lake Park",
  },
  {
    key: "3",
    name: "Ertuğrul",
    surname: "Başköy",
    email: "test@gmail.com",
    phone: "+90 555 555 55 55" ,
    age: 32,
    adress: "New York No. 1 Lake Park",
  },
  {
    key: "4",
    name: "Ertuğrul",
    surname: "Başköy",
    email: "test@gmail.com",
    phone: "+90 555 555 55 55" ,
    age: 32,
    adress: "New York No. 1 Lake Park",
  },
  {
    key: "5",
    name: "Ertuğrul",
    surname: "Başköy",
    email: "test@gmail.com",
    phone: "+90 555 555 55 55" ,
    age: 32,
    adress: "New York No. 1 Lake Park",
  },
  {
    key: "6",
    name: "Ertuğrul",
    surname: "Başköy",
    email: "test@gmail.com",
    phone: "+90 555 555 55 55" ,
    age: 32,
    adress: "New York No. 1 Lake Park",
  },
  {
    key: "7",
    name: "Ertuğrul",
    surname: "Başköy",
    email: "test@gmail.com",
    phone: "+90 555 555 55 55" ,
    age: 32,
    adress: "New York No. 1 Lake Park",
  },
  {
    key: "8",
    name: "Ertuğrul",
    surname: "Başköy",
    email: "test@gmail.com",
    phone: "+90 555 555 55 55" ,
    age: 32,
    adress: "New York No. 1 Lake Park",
  },
  {
    key: "9",
    name: "Ertuğrul",
    surname: "Başköy",
    email: "test@gmail.com",
    phone: "+90 555 555 55 55" ,
    age: 32,
    adress: "New York No. 1 Lake Park",
  },
  {
    key: "10",
    name: "Ertuğrul",
    surname: "Başköy",
    email: "test@gmail.com",
    phone: "+90 555 555 55 55" ,
    age: 32,
    adress: "New York No. 1 Lake Park",
  },
  {
    key: "11",
    name: "Ertuğrul",
    surname: "Başköy",
    email: "test@gmail.com",
    phone: "+90 555 555 55 55" ,
    age: 32,
    adress: "New York No. 1 Lake Park",
  },

];
